
name: 'facebook_ads_creative_history'
version: '0.2.1'
config-version: 2

require-dbt-version: [">=0.18.0", "<0.20.0"]

models:
  facebook_ads_creative_history:
    +schema: facebook_ads_creative_history
    +materialized: table
    bigquery:
      enabled: "{{ target.type == 'bigquery' | as_bool() }}"
    redshift:
      enabled: "{{ target.type == 'redshift' | as_bool() }}"
    snowflake:
      enabled: "{{ target.type == 'snowflake' | as_bool() }}"

vars:
  dbt_utils_dispatch_list: ['spark_utils', 'fivetran_utils']
  fivetran_utils_dispatch_list: ['spark_utils']
