name: 'facebook_ads_creative_history'
version: '0.5.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  facebook_ads_creative_history:
    +schema: facebook_ads_creative_history
    +materialized: table
    bigquery:
      enabled: "{{ target.type == 'bigquery' | as_bool() }}"
    redshift:
      enabled: "{{ target.type == 'redshift' | as_bool() }}"
    snowflake:
      enabled: "{{ target.type == 'snowflake' | as_bool() }}"
    spark:
      enabled: "{{ target.type in ['spark','databricks'] | as_bool() }}"
    postgres:
      enabled: "{{ target.type == 'postgres' | as_bool() }}"
