name: 'facebook_ads_source_integration_tests'
version: '0.5.0'
profile: 'integration_tests'
config-version: 2

vars:
  facebook_ads_source:
    account_history: "{{ ref('facebook_ads_account_history_data') }}"
    ad_history: "{{ ref('facebook_ads_ad_history_data') }}"
    ad_set_history: "{{ ref('facebook_ads_ad_set_history_data') }}"
    basic_ad: "{{ ref('facebook_ads_basic_ad_data') }}"
    campaign_history: "{{ ref('facebook_ads_campaign_history_data') }}"
    creative_history: "{{ ref('facebook_ads_creative_history_data') }}"

seeds:
  facebook_ads_source_integration_tests:
    facebook_ads_creative_history_data:
      +column_types:
        page_link: "{{ 'string' if target.name in ['bigquery','spark'] else 'varchar' }}"
        template_page_link: "{{ 'string' if target.name in ['bigquery','spark'] else 'varchar' }}"
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        account_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        _fivetran_synced: "timestamp"
    facebook_ads_account_history_data:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    facebook_ads_ad_history_data:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        account_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        ad_set_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        creative_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    facebook_ads_ad_set_history_data:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        account_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        campaign_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    facebook_ads_campaign_history_data:
      +column_types:
        id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        account_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
    facebook_ads_basic_ad_data:
      +column_types:
        ad_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        account_id: "{{ 'int64' if target.name == 'bigquery' else 'bigint' }}"
        
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
